variables:
  - group: Milease

  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store

trigger:
  branches:
    include:
      - master

pr: none

jobs:
  - job: BuildProject
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        path: s/MileaseDocument

      - task: Cache@2
        inputs:
          key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
          path: $(pnpm_config_cache)
        displayName: Cache pnpm

      - script: |
          npm install --global corepack@latest
          corepack enable
          corepack prepare pnpm@latest-10 --activate
          pnpm config set store-dir $(pnpm_config_cache)
        displayName: "Setup pnpm"

      - script: |
          cd $(Agent.BuildDirectory)/s/MileaseDocument/
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm run build
        displayName: "pnpm install and build"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Agent.BuildDirectory)/s/MileaseDocument/build"
          publishLocation: "pipeline"
          artifactName: "DocumetpArtifact"

  - job: Deploy
    pool: nk
    dependsOn: BuildProject
    steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: "DocumetpArtifact"
          path: "$(MileaseDocumentWebRoot)"

